export interface ProfileLibraryItem {
  code: string;
  name: string;
  nameEn?: string;
  type: 'Artefato' | 'Livro' | 'Dossiê' | 'Recurso';
  pages?: string;
  credits: number;
  description: string;
  descriptionEn?: string;
  steps: string[];
  stepsEn: string[];
  category: string;
  isUnlockedDefault?: boolean;
}

export interface ProfileLibrarySectionData {
  id: string;
  title: string;
  titleEn: string;
  description: string;
  descriptionEn: string;
  items: ProfileLibraryItem[];
}

export const PROFILE_LIBRARY_SECTIONS: ProfileLibrarySectionData[] = [
  // =========================================================================
  // 1. COMPLETUDE DE PERFIL : ASTROLOGIA
  // =========================================================================
  {
    id: 'perfil-astrologia',
    title: 'Completude de perfil : Astrologia',
    titleEn: 'Profile Completeness : Astrology',
    description: 'Mapas e dossiês fundamentais para ancoragem da matriz natal e arquetípica.',
    descriptionEn: 'Fundamental charts and dossiers for natal and archetypal matrix grounding.',
    items: [
      {
        code: 'AST-001',
        name: 'Mapa Natal - Artefato',
        nameEn: 'Natal Chart - Artifact',
        type: 'Artefato',
        pages: '8-12 páginas',
        credits: 80,
        category: 'Astrologia',
        description: 'Dossiê fundamental das posições planetárias tropicais, casas e aspectos maiores de nascimento. Salvo permanentemente na sua biblioteca.',
        descriptionEn: 'Fundamental tropical planetary positions, houses, and major natal aspects. Saved permanently in your library.',
        steps: [
          'Confirmação de data, horário exato e coordenadas de nascimento.',
          'Cálculo das efemérides astronômicas e determinação da cúspide das casas (Placidus).',
          'Síntese dos luminares (Sol, Lua, Ascendente) e dispositor regente.',
          'Compilação e disponibilização vetorial do artefato na biblioteca.',
        ],
        stepsEn: [
          'Confirmation of exact birth date, time, and geographical coordinates.',
          'Ephemeris calculation and Placidus house cusp determination.',
          'Luminaries synthesis (Sun, Moon, Rising) and ruling dispositor.',
          'Vectorial compilation and permanent storage in your library.',
        ],
      },
      {
        code: 'AST-002',
        name: 'Mapa Sideral - Artefato',
        nameEn: 'Sidereal Chart - Artifact',
        type: 'Artefato',
        pages: '8-12 páginas',
        credits: 80,
        category: 'Astrologia',
        description: 'Cálculo astronômico pelo zodíaco sideral considerando a precessão dos equinócios e ayanamsa Lahiri.',
        descriptionEn: 'Astronomical calculation across the sidereal zodiac considering equinox precession and Lahiri ayanamsa.',
        steps: [
          'Aplicação da correção de Ayanamsa sobre as posições tropicais.',
          'Mapeamento das 27 Nakshatras e posições védicas essenciais.',
          'Cruzamento das dinâmicas de alma e propósito transpessoal.',
          'Renderização do mapa sideral e arquivo PDF do artefato.',
        ],
        stepsEn: [
          'Application of Ayanamsa correction to tropical positions.',
          'Mapping of 27 Nakshatras and essential Vedic alignments.',
          'Cross-referencing soul dynamics and transpersonal purpose.',
          'Rendering of sidereal chart and artifact PDF file.',
        ],
      },
      {
        code: 'AST-005',
        name: 'Mapa Revolução Solar - Artefato',
        nameEn: 'Solar Return Chart - Artifact',
        type: 'Artefato',
        pages: '10-14 páginas',
        credits: 90,
        category: 'Astrologia',
        description: 'Mapeamento do retorno exato do Sol ao seu grau de nascimento para prognóstico e tendências do seu ano pessoal.',
        descriptionEn: 'Mapping the exact return of the Sun to its natal degree for prognostics and personal year trends.',
        steps: [
          'Identificação do momento exato do retorno solar no ano vigente.',
          'Cálculo do Ascendente da Revolução Solar e novo padrão de regência.',
          'Identificação dos meses de ápice e janelas de oportunidade.',
          'Geração do dossiê anual com calendário temático de apoio.',
        ],
        stepsEn: [
          'Identification of exact solar return timestamp for current year.',
          'Calculation of Solar Return Rising sign and active planetary ruler.',
          'Identification of peak months and opportunity windows.',
          'Generation of annual dossier with thematic support calendar.',
        ],
      },
      {
        code: 'AST-006',
        name: 'Mapeamento Comparativo Sideral/Tropical - Artefato',
        nameEn: 'Tropical/Sidereal Comparative Mapping - Artifact',
        type: 'Artefato',
        pages: '14-18 páginas',
        credits: 120,
        category: 'Astrologia',
        description: 'Análise bissetorial comparando a perspectiva psicológica (tropical) e a perspectiva essencial/alma (sideral).',
        descriptionEn: 'Bisectorial comparison between psychological (tropical) and essential/soul (sidereal) astrological perspectives.',
        steps: [
          'Alinhamento em espelho dos mapas Tropical e Sideral.',
          'Identificação das migrações de signos em planetas pessoais.',
          'Síntese da persona externa versus vocação interna essencial.',
          'Geração do relatório comparativo estruturado.',
        ],
        stepsEn: [
          'Mirrored alignment of Tropical and Sidereal charts.',
          'Identification of sign shifts across personal planets.',
          'Synthesis of outer persona vs. inner essential vocation.',
          'Generation of structured comparative report.',
        ],
      },
      {
        code: 'AST-008',
        name: 'Mapa Cronológico Biográfico - Linha Temporal Pessoal Artefato',
        nameEn: 'Chronological Biographical Map - Personal Timeline Artifact',
        type: 'Artefato',
        pages: '16-22 páginas',
        credits: 140,
        category: 'Astrologia',
        description: 'Mapeamento cronológico dos grandes ciclos planetários de vida (retorno de Saturno, quadraturas de Urano, ciclos nodais).',
        descriptionEn: 'Chronological mapping of life planetary cycles (Saturn return, Uranus squares, nodal shifts).',
        steps: [
          'Mapeamento dos septênios e janelas biográficas de 0 a 84 anos.',
          'Cálculo dos trânsitos de planetas lentos sobre pontos angulares.',
          'Identificação de portais de maturidade, transição de carreira e cura.',
          'Emissão do mapa cronológico em formato de linha temporal interativa.',
        ],
        stepsEn: [
          'Mapping septennial cycles and biographical windows from 0 to 84 years.',
          'Calculation of outer planet transits over angular natal points.',
          'Identification of maturity gateways, career shifts, and healing cycles.',
          'Issuance of chronological map as an interactive personal timeline.',
        ],
      },
      {
        code: 'AST-007',
        name: 'Dossiê Astrológico Completo - Mapas Extras',
        nameEn: 'Complete Astrological Dossier - Extra Charts',
        type: 'Dossiê',
        pages: '60-80 páginas',
        credits: 220,
        category: 'Astrologia',
        description: 'Compilação enciclopédica definitiva: Tropical, Sideral, Dracônico, Asteroides, Nódulos Lunares e Estrelas Fixas.',
        descriptionEn: 'Definitive encyclopedic compilation: Tropical, Sidereal, Draconic, Asteroids, Lunar Nodes, and Fixed Stars.',
        steps: [
          'Extração integrada de todas as matrizes astrológicas do usuário.',
          'Cálculo do mapa Dracônico (memória de alma) e 4 grandes asteroides.',
          'Mapeamento de conjunções com Estrelas Fixas de primeira magnitude.',
          'Montagem do livro enciclopédico com encadernação digital completa.',
        ],
        stepsEn: [
          'Integrated extraction of all astrological matrices of user.',
          'Calculation of Draconic chart (soul memory) and 4 major asteroids.',
          'Mapping of exact conjunctions with 1st magnitude Fixed Stars.',
          'Assembly of full encyclopedic volume with digital binding.',
        ],
      },
    ],
  },

  // =========================================================================
  // 2. ARTEFATOS DE PESQUISAS
  // =========================================================================
  {
    id: 'artefatos-pesquisas',
    title: 'Artefatos de Pesquisas',
    titleEn: 'Research Artifacts',
    description: 'Análises dinâmicas de sinastrias, trânsitos sazonais e ciclos periódicos de acompanhamento.',
    descriptionEn: 'Dynamic analyses of synastries, seasonal transits, and periodic monitoring cycles.',
    items: [
      {
        code: 'AST-003',
        name: 'Mapa Composto - Artefato',
        nameEn: 'Composite Chart - Artifact',
        type: 'Artefato',
        pages: '10-14 páginas',
        credits: 100,
        category: 'Pesquisas',
        description: 'Mapa calculado pelo ponto médio das coordenadas de duas pessoas, revelando a terceira entidade energética do vínculo.',
        descriptionEn: 'Midpoint chart between two natal matrixes revealing the third energetic entity of the relationship.',
        steps: [
          'Inserção de dados de nascimento da segunda pessoa.',
          'Cálculo matemático dos pontos médios planetários e casas compostas.',
          'Análise do propósito compartilhado e desafios da parceria.',
          'Emissão do dossiê de relacionamento composto na biblioteca.',
        ],
        stepsEn: [
          'Input birth data of the partner or second entity.',
          'Mathematical midpoint calculation of planets and composite houses.',
          'Analysis of shared purpose and developmental friction points.',
          'Issuance of composite relationship dossier in library.',
        ],
      },
      {
        code: 'AST-009',
        name: 'Mapa Sinastria - Artefato',
        nameEn: 'Synastry Chart - Artifact',
        type: 'Artefato',
        pages: '15-20 páginas',
        credits: 130,
        category: 'Pesquisas',
        description: 'Sinastria detalhada avaliando sobreposição de casas, aspectos interplanetários, atração magnética e afinidade cármica.',
        descriptionEn: 'Detailed synastry analyzing house overlays, interplanetary aspects, magnetic pull, and karmic affinity.',
        steps: [
          'Cruzamento das posições planetárias de ambos os mapas.',
          'Mapeamento dos aspectos interplanetários (conjunções, trígonos, quadraturas).',
          'Diagnóstico de comunicação, intimidade e estabilidade a longo prazo.',
          'Geração do dossiê completo de sinastria relacional.',
        ],
        stepsEn: [
          'Cross-referencing planetary positions of both birth charts.',
          'Mapping interplanetary aspects (conjunctions, trines, squares).',
          'Diagnosis of communication, intimacy, and long-term stability.',
          'Generation of full relational synastry dossier.',
        ],
      },
      {
        code: 'TMP-001',
        name: 'Trânsitos do Mês - Artefato',
        nameEn: 'Monthly Transits - Artifact',
        type: 'Recurso',
        pages: 'Painel Daily Journal + 8 págs',
        credits: 40,
        category: 'Pesquisas',
        description: 'Painel ativo de trânsitos para o mês corrente, integrado ao Daily Journal e arquivado na biblioteca ao final do ciclo.',
        descriptionEn: 'Active monthly transit panel integrated with Daily Journal and permanently archived upon cycle close.',
        steps: [
          'Cálculo dos aspectos formados pelos trânsitos do mês atual sobre o mapa natal.',
          'Identificação das datas de maior potência energética e janelas de cautela.',
          'Ativação do widget de suporte diário no Daily Journal.',
          'Arquivamento do relatório mensal na biblioteca pessoal.',
        ],
        stepsEn: [
          'Calculation of current month transit aspects over natal chart.',
          'Identification of high-potency dates and caution windows.',
          'Activation of daily support widget in Daily Journal.',
          'Permanent archiving of monthly report in personal library.',
        ],
      },
      {
        code: 'TMP-002',
        name: 'Retorno Lunar - Artefato',
        nameEn: 'Lunar Return - Artifact',
        type: 'Recurso',
        pages: 'Painel Daily Journal + 6 págs',
        credits: 40,
        category: 'Pesquisas',
        description: 'Mapeamento do humor psicoemocional e foco do mês a cada 27,3 dias. Atua como suporte no Daily Journal.',
        descriptionEn: 'Psycho-emotional mood mapping and monthly focus every 27.3 days. Acts as support in Daily Journal.',
        steps: [
          'Identificação do momento exato do retorno da Lua ao grau natal.',
          'Cálculo do Ascendente lunar do ciclo de 28 dias.',
          'Recomendações emocionais, metabólicas e de ritmo circadiano.',
          'Disponibilização do relatório na biblioteca.',
        ],
        stepsEn: [
          'Identification of exact moment Moon returns to natal degree.',
          'Calculation of Lunar Return Ascendant for the 28-day cycle.',
          'Emotional, metabolic, and circadian rhythm recommendations.',
          'Report issuance and library storage.',
        ],
      },
      {
        code: 'TMP-003',
        name: 'Progressões Secundárias - Artefato',
        nameEn: 'Secondary Progressions - Artifact',
        type: 'Artefato',
        pages: 'Painel Daily Journal + 10 págs',
        credits: 50,
        category: 'Pesquisas',
        description: 'Acompanhamento do amadurecimento psicológico e mudanças arquetípicas da consciência no apoio diário.',
        descriptionEn: 'Tracking psychological maturation and archetypal shifts in consciousness in daily journal support.',
        steps: [
          'Aplicação da fórmula 1 dia pós-nascimento = 1 ano de vida.',
          'Cálculo da Lua Progredida e transição de signos do Sol Progredido.',
          'Diagnóstico de ciclos de interiorização versus ciclos de expansão.',
          'Geração do dossiê de progressões secundárias.',
        ],
        stepsEn: [
          'Application of 1 day after birth = 1 year of life formula.',
          'Calculation of Progressed Moon and Progressed Sun sign transitions.',
          'Diagnosis of inward introspection vs. outward expansion cycles.',
          'Generation of secondary progressions dossier.',
        ],
      },
      {
        code: 'TMP-004',
        name: 'Ano Pessoal - Artefato',
        nameEn: 'Personal Year - Artifact',
        type: 'Recurso',
        pages: 'Painel Anual + 14 págs',
        credits: 70,
        category: 'Pesquisas',
        description: 'Vibração anual numerológica profunda com meses pessoais detalhados. Alimenta os painéis de apoio e a biblioteca.',
        descriptionEn: 'Deep annual numerological vibration with detailed personal months. Feeds support panels and library.',
        steps: [
          'Cálculo do número regente do Ano Pessoal (dia + mês + ano universal).',
          'Estruturação dos 12 Meses Pessoais e seus respectivos desafios.',
          'Integração com metas estratégicas e tomada de decisão.',
          'Geração da cartilha anual completa para a biblioteca.',
        ],
        stepsEn: [
          'Calculation of Personal Year ruling number (day + month + universal year).',
          'Structuring the 12 Personal Months and their respective challenges.',
          'Integration with strategic goals and decisive timing.',
          'Generation of complete annual handbook for library.',
        ],
      },
      {
        code: 'TMP-005',
        name: 'Anuário de Trânsitos - Artefato',
        nameEn: 'Annual Transits Almanac - Artifact',
        type: 'Recurso',
        pages: 'Painel Anual + 20 págs',
        credits: 90,
        category: 'Pesquisas',
        description: 'Guia anual completo com todos os ciclos de planetas lentos, eclipses e lunações integrados ao seu acompanhamento.',
        descriptionEn: 'Full 12-month guide with all outer planet cycles, eclipses, and retrogrades integrated into your guidance.',
        steps: [
          'Mapeamento dos 365 dias do ano em relação à matriz natal.',
          'Destacar eclipses solares e lunares que ativam casas e eixos vitais.',
          'Cronograma de retrogradações de Mercúrio, Vênus e Marte.',
          'Publicação do anuário encadernado digitalmente.',
        ],
        stepsEn: [
          'Mapping 365 days of the year relative to natal matrix.',
          'Highlighting solar and lunar eclipses activating vital houses and axes.',
          'Schedule of Mercury, Venus, and Mars retrograde windows.',
          'Publication of digitally bound almanac.',
        ],
      },
    ],
  },

  // =========================================================================
  // 3. COMPLETUDE DE PERFIL : CABALA / TAROT
  // =========================================================================
  {
    id: 'perfil-cabala-tarot',
    title: 'Completude de Perfil : Cabala/Tarot',
    titleEn: 'Profile Completeness : Kabbalah/Tarot',
    description: 'Tratados arquetípicos, geometria sagrada da Árvore da Vida e decodificação gemátrica.',
    descriptionEn: 'Archetypal treatises, sacred geometry of Tree of Life, and gematric decoding.',
    items: [
      {
        code: 'CAB-002',
        name: 'Árvore da Vida Judaica - Artefato',
        nameEn: 'Jewish Tree of Life - Artifact',
        type: 'Artefato',
        pages: '10-14 páginas',
        credits: 90,
        category: 'Cabala',
        description: 'Mapeamento pessoal das 10 Sefirot, pilares do equilíbrio (Misericórdia, Rigor e Equilíbrio) e mundos da criação.',
        descriptionEn: 'Personal mapping of the 10 Sefirot, pillars of balance (Mercy, Severity, Balance), and creation realms.',
        steps: [
          'Transliteração hebraica do nome completo e data de nascimento.',
          'Cálculo das Sefirot de entrada, fixação e Tikun (correção da alma).',
          'Mapeamento dos 3 Pilares e distribuição de energias ativas.',
          'Renderização do glifo da Árvore da Vida personalizado.',
        ],
        stepsEn: [
          'Hebrew transliteration of full name and birth date.',
          'Calculation of entry Sefirot, fixation, and Tikun (soul rectification).',
          'Mapping the 3 Pillars and active energy distributions.',
          'Rendering of custom personalized Tree of Life glyph.',
        ],
      },
      {
        code: 'CAB-001',
        name: 'Gematria Judaica - Artefato',
        nameEn: 'Jewish Gematria - Artifact',
        type: 'Artefato',
        pages: '8-10 páginas',
        credits: 80,
        category: 'Cabala',
        description: 'Decodificação dos valores numéricos do nome em hebraico, equivalências bíblicas e frequências vibratórias da alma.',
        descriptionEn: 'Hebrew name gematric values decoding, biblical equivalences, and spiritual soul vibration frequencies.',
        steps: [
          'Cálculo pelos métodos Gematria Absoluta (Ragil) e Reduzida (Katan).',
          'Identificação de palavras-chave da Torá com valor numérico equivalente.',
          'Revelação do propósito oculto e vocação espiritual.',
          'Compilação do dossiê gemátrico na biblioteca.',
        ],
        stepsEn: [
          'Calculation using Absolute (Ragil) and Reduced (Katan) Gematria.',
          'Identification of Torah keywords sharing equivalent numeric values.',
          'Revelation of hidden purpose and spiritual soul vocation.',
          'Compilation of gematric dossier in personal library.',
        ],
      },
      {
        code: 'CAB-003',
        name: 'Análise de Letras Hebraicas - Artefato',
        nameEn: 'Hebrew Letters Analysis - Artifact',
        type: 'Artefato',
        pages: '8-12 páginas',
        credits: 80,
        category: 'Cabala',
        description: 'Estudo dos canais arquetípicos das 22 letras hebraicas associadas ao seu nome e matriz natal (Tikun pessoal).',
        descriptionEn: 'Study of the 22 Hebrew letter archetypal channels associated with your name and natal matrix (personal Tikun).',
        steps: [
          'Decomposição das letras mães, duplas e simples da assinatura energética.',
          'Associação das letras com os canais da Árvore da Vida.',
          'Identificação das forças de manifestação e pontos cegos.',
          'Emissão do guia visual das letras sagradas na biblioteca.',
        ],
        stepsEn: [
          'Decomposition of Mother, Double, and Simple letters of signature.',
          'Association of letters with Tree of Life connecting paths.',
          'Identification of manifestation channels and blind spots.',
          'Issuance of sacred letters visual guide in library.',
        ],
      },
      {
        code: 'CAB-004',
        name: 'Perfil Arquetípico do Tarot - Artefato',
        nameEn: 'Tarot Archetypal Profile - Artifact',
        type: 'Artefato',
        pages: '8-10 páginas',
        credits: 80,
        category: 'Tarot',
        description: 'Cálculo dos Arcanos Maiores de Nascimento (Lição de Vida, Personalidade e Ano Arquetípico).',
        descriptionEn: 'Birth Major Arcana calculation (Soul Lesson, Personality, and Archetypal Year).',
        steps: [
          'Redução teosófica da data de nascimento para extração do Arcano Maior.',
          'Cálculo do Arcano de Lição de Alma e Arcano de Personalidade.',
          'Mapeamento dos ciclos de sombra e maestria arquetípica.',
          'Renderização das lâminas arquetípicas no dossiê pessoal.',
        ],
        stepsEn: [
          'Theosophical reduction of birth date to extract core Major Arcana.',
          'Calculation of Soul Lesson Arcana and Personality Arcana.',
          'Mapping shadow cycles and archetypal mastery pathways.',
          'Rendering of archetypal blades inside personal dossier.',
        ],
      },
      {
        code: 'CAB-006',
        name: 'Árvore da Vida Hermética - Artefato',
        nameEn: 'Hermetic Tree of Life - Artifact',
        type: 'Artefato',
        pages: '10-14 páginas',
        credits: 90,
        category: 'Cabala',
        description: 'Estruturação dos 32 Caminhos da Sabedoria com atribuições astrológicas e os 22 Arcanos Maiores nos caminhos.',
        descriptionEn: 'Structuring the 32 Paths of Wisdom with astrological correspondences and 22 Major Arcana across paths.',
        steps: [
          'Mapeamento dos 22 caminhos de conexão entre as Sefirot.',
          'Associação com elementos alquímicos, signos e planetas clássicos.',
          'Diagnóstico de circulação da força vital nos 4 Mundos Herméticos.',
          'Emissão do tratado hermético ilustrado.',
        ],
        stepsEn: [
          'Mapping 22 connecting paths between Sefirot.',
          'Association with alchemical elements, signs, and classical planets.',
          'Diagnosis of vital force circulation across 4 Hermetic Worlds.',
          'Issuance of illustrated hermetic treatise.',
        ],
      },
      {
        code: 'CAB-007',
        name: 'Correspondências Herméticas Planetárias - Artefato',
        nameEn: 'Hermetic Planetary Correspondences - Artifact',
        type: 'Artefato',
        pages: '12-16 páginas',
        credits: 100,
        category: 'Cabala',
        description: 'Tabelas e síntese de inteligências, espíritos, selos, metais e perfumes dos sete planetas tradicionais.',
        descriptionEn: 'Tables and synthesis of intelligences, spirits, seals, metals, and scents of the seven classical planets.',
        steps: [
          'Determinação do planeta dominante e dispositor alquímico.',
          'Compilação de tabelas de correspondências tradicionais (Agrippa/Picatrix).',
          'Recomendações práticas de ancoragem energética por frequência.',
          'Disponibilização do manual na biblioteca.',
        ],
        stepsEn: [
          'Determination of dominant planet and alchemical dispositor.',
          'Compilation of traditional correspondence tables (Agrippa/Picatrix).',
          'Actionable recommendations for frequency grounding.',
          'Manual availability in personal library.',
        ],
      },
      {
        code: 'CAB-005',
        name: 'Análise Tarot Pessoal - Artefato',
        nameEn: 'Personal Tarot Analysis - Artifact',
        type: 'Livro',
        pages: '30-45 páginas',
        credits: 160,
        category: 'Tarot',
        description: 'Tratado completo das lâminas pessoais, cortes arquetípicas, jornadas do herói e integração de sombras.',
        descriptionEn: 'Full treatise on personal blades, archetypal courts, hero journey stages, and shadow integration.',
        steps: [
          'Mapeamento aprofundado dos 78 arcanos relacionados à assinatura pessoal.',
          'Análise detalhada das 16 figuras da corte e papéis sociais.',
          'Jornada de individuação junguiana orientada pelos arcanos.',
          'Compilação do livro analítico completo de Tarot.',
        ],
        stepsEn: [
          'In-depth mapping of 78 arcana related to personal signature.',
          'Detailed analysis of 16 court cards and social roles.',
          'Jungian individuation journey guided by the arcana.',
          'Compilation of complete analytical Tarot volume.',
        ],
      },
    ],
  },

  // =========================================================================
  // 4. COMPLETUDE DE PERFIL : NUMEROLÓGICO CABALÍSTICO
  // =========================================================================
  {
    id: 'perfil-numerologia',
    title: 'Completude de Perfil : Numerológico Cabalístico',
    titleEn: 'Profile Completeness : Cabalistic Numerology',
    description: 'Arquitetura matemática do destino, pináculos de vida, pirâmides numéricas e grande síntese.',
    descriptionEn: 'Mathematical destiny architecture, life pinnacles, numerical pyramids, and master synthesis.',
    items: [
      {
        code: 'CAB-008',
        name: 'Dossiê Numerológico Cabalístico - Artefato',
        nameEn: 'Cabalistic Numerology Dossier - Artifact',
        type: 'Artefato',
        pages: '14-18 páginas',
        credits: 110,
        category: 'Numerologia',
        description: 'Integração de valores gemátricos, matriz de letras sagradas e posições das Sefirot em uma única leitura.',
        descriptionEn: 'Integration of gematric values, sacred letter matrix, and Sefirotic positions in a single cohesive reading.',
        steps: [
          'Conversão do nome para valores numéricos cabalísticos.',
          'Cruzamento das vibrações com as 10 Sefirot da Árvore da Vida.',
          'Mapeamento de dívidas cármicas e talentos inatos.',
          'Geração do dossiê híbrido na biblioteca.',
        ],
        stepsEn: [
          'Conversion of name into cabalistic numerical values.',
          'Cross-referencing vibrations with 10 Sefirot of Tree of Life.',
          'Mapping karmic debts and innate spiritual gifts.',
          'Generation of hybrid dossier in personal library.',
        ],
      },
      {
        code: 'CAB-009',
        name: 'Dossiê Cabalístico Completo - Artefato',
        nameEn: 'Complete Cabalistic Dossier - Artifact',
        type: 'Dossiê',
        pages: '50-70 páginas',
        credits: 220,
        category: 'Cabala',
        description: 'O compêndio cabalístico definitivo: Gematria, 72 Nomes de Deus, Tikun, Árvore Judaica e Hermética.',
        descriptionEn: 'The definitive cabalistic compendium: Gematria, 72 Names of God, Tikun, Jewish and Hermetic Tree.',
        steps: [
          'Integração enciclopédica de todas as matrizes cabalísticas do usuário.',
          'Cálculo das 3 tríades dos 72 Nomes de Deus associadas ao nascimento.',
          'Diagnóstico do plano de encarnação e desafios de alma.',
          'Publicação do grande compêndio na biblioteca.',
        ],
        stepsEn: [
          'Encyclopedic integration of all user cabalistic matrices.',
          'Calculation of 3 triads of 72 Names of God linked to birth.',
          'Diagnosis of incarnation plan and soul challenges.',
          'Publication of grand compendium in personal library.',
        ],
      },
      {
        code: 'NUM-001',
        name: 'Dossiê Numerologia Completa - Artefato',
        nameEn: 'Complete Numerology Dossier - Artifact',
        type: 'Artefato',
        pages: '8-12 páginas',
        credits: 80,
        category: 'Numerologia',
        description: 'Mapa pitagórico base: Alma (Motivação), Aparência (Impressão), Destino (Expressão) e Missão de Vida.',
        descriptionEn: 'Core Pythagorean chart: Soul (Motivation), Outer (Impression), Destiny (Expression), and Life Mission.',
        steps: [
          'Cálculo das vogais (Alma) e consoantes (Aparência).',
          'Soma total do nome (Destino) e data de nascimento (Missão).',
          'Análise do Número Psíquico e Números de Apoio.',
          'Disponibilização do mapa numerológico na biblioteca.',
        ],
        stepsEn: [
          'Calculation of vowels (Soul) and consonants (Outer impression).',
          'Total sum of name (Destiny) and birth date (Life Mission).',
          'Analysis of Psychic Number and auxiliary vibration nodes.',
          'Delivery of numerological chart to personal library.',
        ],
      },
      {
        code: 'NUM-002',
        name: 'Ciclos de Vida Numerológicos - Artefato',
        nameEn: 'Numerological Life Cycles - Artifact',
        type: 'Artefato',
        pages: '8-12 páginas',
        credits: 80,
        category: 'Numerologia',
        description: 'Mapeamento temporal dos 3 Grandes Ciclos de Vida, 4 Pináculos de Realização e 3 Momentos de Desafio.',
        descriptionEn: 'Temporal mapping of the 3 Major Life Cycles, 4 Realization Pinnacles, and 3 Challenge Phases.',
        steps: [
          'Cálculo dos 3 Ciclos Formativos (Juventude, Produtivo, Colheita).',
          'Determinação das idades de transição dos 4 Pináculos.',
          'Mapeamento dos Números de Desafio que exigem superação.',
          'Emissão da régua cronológica de vida na biblioteca.',
        ],
        stepsEn: [
          'Calculation of 3 Formative Cycles (Youth, Productivity, Harvest).',
          'Determination of transition ages for the 4 Pinnacles.',
          'Mapping Challenge Numbers that demand conscious mastery.',
          'Issuance of chronological life ruler in personal library.',
        ],
      },
      {
        code: 'NUM-004',
        name: 'Livro de Análise Numerológica Completa - Artefato',
        nameEn: 'Complete Numerological Analysis Book - Artifact',
        type: 'Livro',
        pages: '35-50 páginas',
        credits: 160,
        category: 'Numerologia',
        description: 'Tratado enciclopédico de todos os números do seu ser: vibração de letras, tendências ocultas e compatibilidades.',
        descriptionEn: 'Encyclopedic treatise of all numbers: letter vibrations, hidden tendencies, and universal compatibility.',
        steps: [
          'Análise detalhada de cada letra individual do nome de batismo.',
          'Cálculo de excessos e carências na Grade Numérica Pitagórica.',
          'Compatibilidade vibracional e tendências de realização.',
          'Encadernação digital do livro analítico completo.',
        ],
        stepsEn: [
          'Detailed analysis of every individual letter of birth name.',
          'Calculation of excesses and voids on Pythagorean Number Grid.',
          'Vibrational compatibility and realization predispositions.',
          'Digital binding of complete analytical book volume.',
        ],
      },
      {
        code: 'NUM-003',
        name: 'Pirâmide Numerológica - Artefato',
        nameEn: 'Numerological Pyramid - Artifact',
        type: 'Artefato',
        pages: '10-14 páginas',
        credits: 90,
        category: 'Numerologia',
        description: 'Método da Pirâmide Invertida para detecção de arcanos repetitivos, bloqueios energéticos e sequências cármicas.',
        descriptionEn: 'Inverted Pyramid method revealing repeating arcana blocks, energetic locks, and karmic sequences.',
        steps: [
          'Montagem da matriz triangular invertida a partir do nome.',
          'Detecção de Sequências Cármicas (arcanos repetidos 3+ vezes).',
          'Orientações práticas de desbloqueio de padrões ancestrais.',
          'Geração do diagrama geométrico da pirâmide.',
        ],
        stepsEn: [
          'Construction of inverted triangular matrix from full name.',
          'Detection of Karmic Sequences (arcana repeated 3+ times).',
          'Practical guidance for unlocking ancestral cyclical patterns.',
          'Generation of pyramid geometric diagram.',
        ],
      },
      {
        code: 'CHV-001',
        name: 'Perfil Simbólico Integrado - Grande Dossiê',
        nameEn: 'Integrated Symbolic Profile - Grand Master Dossier',
        type: 'Dossiê',
        pages: '80-120 páginas',
        credits: 300,
        category: 'Chave Mestra',
        description: 'A obra máxima de completude: fusão algorítmica e simbólica de Astrologia, Numerologia, Cabala e Tarot em um único tratado pessoal.',
        descriptionEn: 'The master pinnacle of personal completude: algorithmic synthesis of Astrology, Numerology, Kabbalah, and Tarot.',
        steps: [
          'Unificação algorítmica de todas as 4 tradições de sabedoria.',
          'Síntese holística de arquétipos dominantes, propósito e destino.',
          'Cruzamento de trânsitos futuros, ciclos numerológicos e Tikun.',
          'Emissão da obra-prima enciclopédica do usuário na biblioteca.',
        ],
        stepsEn: [
          'Algorithmic unification of all 4 wisdom traditions.',
          'Holistic synthesis of dominant archetypes, purpose, and destiny.',
          'Cross-referencing future transits, numerological cycles, and Tikun.',
          'Issuance of user masterpiece encyclopedic volume in library.',
        ],
      },
    ],
  },

  // =========================================================================
  // 5. BIBLIOTECA USUÁRIO : LIVROS DE ANÁLISES
  // =========================================================================
  {
    id: 'biblioteca-livros',
    title: 'Biblioteca Usuário : Livros de Análises',
    titleEn: 'User Library : Analytical Books',
    description: 'Edições enciclopédicas aprofundadas em formato de livro para estudo e consulta vitalícia.',
    descriptionEn: 'Deep encyclopedic editions in book format for lifetime study and consultation.',
    items: [
      {
        code: 'BK-AST-001',
        name: 'Mapa Natal - Livro',
        nameEn: 'Natal Chart - Book',
        type: 'Livro',
        pages: '35-50 páginas',
        credits: 180,
        category: 'Livros de Análises',
        description: 'Tratado aprofundado e minucioso de cada posicionamento planetário, dispositor, regências e padrões de aspectos.',
        descriptionEn: 'Exhaustive treatise on every placement, dispositor, rulership, and aspect patterns of your matrix.',
        steps: [
          'Compilação de cada casa astrológica e planeta com textos extensos.',
          'Análise de regentes de casas, aspectos menores e orbes precisas.',
          'Geração de índices e capítulos formatados para leitura densa.',
          'Entrega do livro em formato de publicação digital permanente.',
        ],
        stepsEn: [
          'Compilation of every astrological house and planet with extensive texts.',
          'Analysis of house rulers, minor aspects, and precise orb degrees.',
          'Generation of table of contents and formatted chapters for reading.',
          'Delivery of book in permanent digital publication format.',
        ],
      },
      {
        code: 'BK-AST-002',
        name: 'Mapa Sideral - Livro',
        nameEn: 'Sidereal Chart - Book',
        type: 'Livro',
        pages: '35-45 páginas',
        credits: 180,
        category: 'Livros de Análises',
        description: 'Compêndio sideral aprofundado com análise das Nakshatras, mapas divisionais D9 (Navamsha) e regências cármicas.',
        descriptionEn: 'In-depth sidereal compendium with Nakshatras analysis, D9 Navamsha divisional charts, and karmic rulerships.',
        steps: [
          'Cálculo do mapa Rashi (D1) e mapa divisional Navamsha (D9).',
          'Estudo minucioso das 27 mansões lunares (Nakshatras).',
          'Interpretação das Dhasas (períodos planetários de vida).',
          'Emissão do livro védico/sideral encadernado digitalmente.',
        ],
        stepsEn: [
          'Calculation of Rashi (D1) chart and Navamsha (D9) divisional chart.',
          'Thorough study of the 27 lunar mansions (Nakshatras).',
          'Interpretation of Dhasas (planetary life periods).',
          'Issuance of Vedic/Sidereal digitally bound volume.',
        ],
      },
      {
        code: 'BK-AST-005',
        name: 'Mapa Revolução Solar - Livro',
        nameEn: 'Solar Return - Book',
        type: 'Livro',
        pages: '30-40 páginas',
        credits: 180,
        category: 'Livros de Análises',
        description: 'Livro analítico do ano com prognóstico mês a mês, revoluções lunares subsidiárias e guias de decisão estratégica.',
        descriptionEn: 'Annual analytical book with month-by-month prognostic, subsidiary lunar returns, and strategic decision guides.',
        steps: [
          'Análise profunda do Ascendente da Revolução e casa ocupada pelo Sol.',
          'Detalhamento dos 12 meses do ano solar com gráficos de energia.',
          'Estratégias para negócios, saúde, relacionamentos e foco mental.',
          'Compilação do volume anual com índice remissivo.',
        ],
        stepsEn: [
          'Deep analysis of Solar Return Rising sign and natal house occupied by Sun.',
          'Detailing all 12 solar year months with energetic trend graphs.',
          'Strategies for career, vitality, relationships, and mental focus.',
          'Compilation of annual volume with cross-reference index.',
        ],
      },
      {
        code: 'BK-AST-006',
        name: 'Mapeamento Comparativo Sideral/Tropical - Livro',
        nameEn: 'Tropical/Sidereal Comparative - Book',
        type: 'Livro',
        pages: '35-50 páginas',
        credits: 200,
        category: 'Livros de Análises',
        description: 'Tratado completo sobre a ponte entre a personalidade humana (Tropical) e a consciência cósmica (Sideral).',
        descriptionEn: 'Complete treatise bridging human personality (Tropical) and cosmic consciousness (Sidereal).',
        steps: [
          'Análise comparativa planeta por planeta e casa por casa.',
          'Estudo de casos de transição e dissonância cognitiva arquetípica.',
          'Técnicas de integração e harmonização das duas matrizes.',
          'Publicação do livro comparativo na biblioteca do usuário.',
        ],
        stepsEn: [
          'Planet-by-planet and house-by-house comparative analysis.',
          'Study of transition points and archetypal cognitive harmonization.',
          'Integration techniques for bridging the two matrices.',
          'Publication of comparative volume in user personal library.',
        ],
      },
      {
        code: 'BK-AST-008',
        name: 'Mapa Cronológico Biográfico - Linha Temporal Pessoal Livro',
        nameEn: 'Chronological Biographical Map - Personal Timeline Book',
        type: 'Livro',
        pages: '40-60 páginas',
        credits: 220,
        category: 'Livros de Análises',
        description: 'O livro definitivo da sua vida: análise detalhada de cada ciclo de 7 anos, trânsitos históricos e previsões futuras.',
        descriptionEn: 'The definitive biographical book of your life: detailed 7-year cycle analyses, historical transits, and future forecasts.',
        steps: [
          'Estruturação dos 12 septênios da vida humana.',
          'Mapeamento retrospectivo dos grandes marcos e crises de transformação.',
          'Projeção de janelas futuras de oportunidade até a maturidade plena.',
          'Encadernação digital da biografia cronológica definitiva.',
        ],
        stepsEn: [
          'Structuring the 12 septennials of human life.',
          'Retrospective mapping of major transformational milestones and crises.',
          'Projection of future opportunity windows into full maturity.',
          'Digital binding of the definitive chronological biography.',
        ],
      },
    ],
  },
];
