import {
  Sparkles,
  Flame,
  Target,
  Sun,
  Moon,
  ShieldCheck,
  Zap,
  Compass,
  HeartPulse,
  CheckCircle2,
  LucideIcon,
  Activity,
  Layers,
  FileText,
  Volume2,
  Calendar,
  Briefcase,
  Laptop,
  Presentation,
  Paperclip,
  Mail,
  TrendingUp,
  Folder,
  Gamepad2,
  Dumbbell,
  Music,
  Film,
  BookOpen,
  Plane,
  Bike,
  Camera,
  Tv,
  Palmtree,
  Trophy,
  Smile,
  Heart,
  Eye,
  SmilePlus,
  Laugh,
  PartyPopper,
  HeartHandshake,
  Trees,
  Flower2,
  Leaf,
  Mountain,
  Wind,
  Droplets,
  CloudSun,
  Sunset,
  Sunrise,
  Bird,
  Feather,
  Waves,
  Sprout,
  Utensils,
  Coffee,
  Wine,
  Pizza,
  Apple,
  Cake,
  Cookie,
  CupSoda,
  Sandwich,
  Beer,
  Soup,
  Salad,
  Home,
  Users,
  Baby,
  Brain,
  AlertCircle,
  CloudRain,
  Snowflake,
  CloudLightning,
  Cat,
  Dog,
  ListTodo,
  Rocket,
  BarChart2,
  Clock,
  Flag,
} from 'lucide-react';
import { CheckPointAttachedItem } from '../../types';

export interface CheckpointColorOption {
  id: string;
  name: string;
  namePt: string;
  group: 'main' | 'light' | 'dark';
  isSubtone?: boolean;
  parentColorId?: string;
  bgClass: string;
  textClass: string;
  borderClass: string;
  badgeClass: string;
  glowClass: string;
  hex: string;
}

// 36 Color Options: 12 Main colors, 12 Light Subtones, 12 Dark Subtones
export const CHECKPOINT_COLORS: CheckpointColorOption[] = [
  // =========================================================================
  // 12 CORES PRINCIPAIS
  // =========================================================================
  {
    id: 'blue',
    name: 'Cobalt Blue',
    namePt: 'Azul Soberano',
    group: 'main',
    isSubtone: false,
    bgClass: 'bg-blue-500/15',
    textClass: 'text-blue-600 dark:text-blue-400',
    borderClass: 'border-blue-500/40',
    badgeClass: 'bg-blue-600 text-white',
    glowClass: 'shadow-blue-500/20',
    hex: '#2563eb',
  },
  {
    id: 'emerald',
    name: 'Emerald Harmony',
    namePt: 'Esmeralda Alinhamento',
    group: 'main',
    isSubtone: false,
    bgClass: 'bg-emerald-500/15',
    textClass: 'text-emerald-600 dark:text-emerald-400',
    borderClass: 'border-emerald-500/40',
    badgeClass: 'bg-emerald-500 text-white',
    glowClass: 'shadow-emerald-500/20',
    hex: '#10b981',
  },
  {
    id: 'indigo',
    name: 'Indigo Insight',
    namePt: 'Índigo Profundo',
    group: 'main',
    isSubtone: false,
    bgClass: 'bg-indigo-500/15',
    textClass: 'text-indigo-600 dark:text-indigo-400',
    borderClass: 'border-indigo-500/40',
    badgeClass: 'bg-indigo-500 text-white',
    glowClass: 'shadow-indigo-500/20',
    hex: '#6366f1',
  },
  {
    id: 'amber',
    name: 'Solar Amber',
    namePt: 'Âmbar Solar',
    group: 'main',
    isSubtone: false,
    bgClass: 'bg-amber-500/15',
    textClass: 'text-amber-600 dark:text-amber-400',
    borderClass: 'border-amber-500/40',
    badgeClass: 'bg-amber-500 text-white',
    glowClass: 'shadow-amber-500/20',
    hex: '#f59e0b',
  },
  {
    id: 'rose',
    name: 'Rose Vitality',
    namePt: 'Rubi Vitalidade',
    group: 'main',
    isSubtone: false,
    bgClass: 'bg-rose-500/15',
    textClass: 'text-rose-600 dark:text-rose-400',
    borderClass: 'border-rose-500/40',
    badgeClass: 'bg-rose-500 text-white',
    glowClass: 'shadow-rose-500/20',
    hex: '#f43f5e',
  },
  {
    id: 'purple',
    name: 'Amethyst Transcendence',
    namePt: 'Ametista Transcendência',
    group: 'main',
    isSubtone: false,
    bgClass: 'bg-purple-500/15',
    textClass: 'text-purple-600 dark:text-purple-400',
    borderClass: 'border-purple-500/40',
    badgeClass: 'bg-purple-500 text-white',
    glowClass: 'shadow-purple-500/20',
    hex: '#a855f7',
  },
  {
    id: 'cyan',
    name: 'Cyan Clarity',
    namePt: 'Ciano Clareza',
    group: 'main',
    isSubtone: false,
    bgClass: 'bg-cyan-500/15',
    textClass: 'text-cyan-600 dark:text-cyan-400',
    borderClass: 'border-cyan-500/40',
    badgeClass: 'bg-cyan-500 text-white',
    glowClass: 'shadow-cyan-500/20',
    hex: '#06b6d4',
  },
  {
    id: 'slate',
    name: 'Sovereign Slate',
    namePt: 'Grafite Soberano',
    group: 'main',
    isSubtone: false,
    bgClass: 'bg-slate-500/15',
    textClass: 'text-slate-700 dark:text-slate-300',
    borderClass: 'border-slate-500/40',
    badgeClass: 'bg-slate-700 text-white',
    glowClass: 'shadow-slate-500/20',
    hex: '#64748b',
  },
  {
    id: 'red',
    name: 'Crimson Focus',
    namePt: 'Vermelho Carmim',
    group: 'main',
    isSubtone: false,
    bgClass: 'bg-red-500/15',
    textClass: 'text-red-600 dark:text-red-400',
    borderClass: 'border-red-500/40',
    badgeClass: 'bg-red-600 text-white',
    glowClass: 'shadow-red-500/20',
    hex: '#dc2626',
  },
  {
    id: 'orange',
    name: 'Solar Orange',
    namePt: 'Laranja Radiante',
    group: 'main',
    isSubtone: false,
    bgClass: 'bg-orange-500/15',
    textClass: 'text-orange-600 dark:text-orange-400',
    borderClass: 'border-orange-500/40',
    badgeClass: 'bg-orange-500 text-white',
    glowClass: 'shadow-orange-500/20',
    hex: '#ea580c',
  },
  {
    id: 'lime',
    name: 'Vibrant Lime',
    namePt: 'Lima Desperto',
    group: 'main',
    isSubtone: false,
    bgClass: 'bg-lime-500/15',
    textClass: 'text-lime-700 dark:text-lime-400',
    borderClass: 'border-lime-500/40',
    badgeClass: 'bg-lime-600 text-white',
    glowClass: 'shadow-lime-500/20',
    hex: '#84cc16',
  },
  {
    id: 'gold',
    name: 'Warm Gold',
    namePt: 'Ouro Alquímico',
    group: 'main',
    isSubtone: false,
    bgClass: 'bg-yellow-500/15',
    textClass: 'text-yellow-700 dark:text-yellow-400',
    borderClass: 'border-yellow-500/40',
    badgeClass: 'bg-yellow-600 text-white',
    glowClass: 'shadow-yellow-500/20',
    hex: '#d97706',
  },

  // =========================================================================
  // 12 SUBTONS MAIS CLAROS (PASTEL / SUAVES)
  // =========================================================================
  {
    id: 'blue-light',
    name: 'Sky Blue Light',
    namePt: 'Azul Céu Claro',
    group: 'light',
    isSubtone: true,
    parentColorId: 'blue',
    bgClass: 'bg-blue-300/20',
    textClass: 'text-blue-700 dark:text-blue-300',
    borderClass: 'border-blue-300/50',
    badgeClass: 'bg-blue-400 text-slate-900',
    glowClass: 'shadow-blue-300/20',
    hex: '#93c5fd',
  },
  {
    id: 'emerald-light',
    name: 'Mint Light',
    namePt: 'Menta Suave',
    group: 'light',
    isSubtone: true,
    parentColorId: 'emerald',
    bgClass: 'bg-emerald-300/20',
    textClass: 'text-emerald-700 dark:text-emerald-300',
    borderClass: 'border-emerald-300/50',
    badgeClass: 'bg-emerald-400 text-slate-900',
    glowClass: 'shadow-emerald-300/20',
    hex: '#6ee7b7',
  },
  {
    id: 'indigo-light',
    name: 'Lavender Light',
    namePt: 'Lavanda Clara',
    group: 'light',
    isSubtone: true,
    parentColorId: 'indigo',
    bgClass: 'bg-indigo-300/20',
    textClass: 'text-indigo-700 dark:text-indigo-300',
    borderClass: 'border-indigo-300/50',
    badgeClass: 'bg-indigo-400 text-white',
    glowClass: 'shadow-indigo-300/20',
    hex: '#a5b4fc',
  },
  {
    id: 'amber-light',
    name: 'Peach Light',
    namePt: 'Pêssego Claro',
    group: 'light',
    isSubtone: true,
    parentColorId: 'amber',
    bgClass: 'bg-amber-300/20',
    textClass: 'text-amber-800 dark:text-amber-300',
    borderClass: 'border-amber-300/50',
    badgeClass: 'bg-amber-400 text-slate-900',
    glowClass: 'shadow-amber-300/20',
    hex: '#fcd34d',
  },
  {
    id: 'rose-light',
    name: 'Rose Petal Light',
    namePt: 'Rosa Pétala Claro',
    group: 'light',
    isSubtone: true,
    parentColorId: 'rose',
    bgClass: 'bg-rose-300/20',
    textClass: 'text-rose-700 dark:text-rose-300',
    borderClass: 'border-rose-300/50',
    badgeClass: 'bg-rose-400 text-slate-900',
    glowClass: 'shadow-rose-300/20',
    hex: '#fda4af',
  },
  {
    id: 'purple-light',
    name: 'Lilac Light',
    namePt: 'Lilás Claro',
    group: 'light',
    isSubtone: true,
    parentColorId: 'purple',
    bgClass: 'bg-purple-300/20',
    textClass: 'text-purple-700 dark:text-purple-300',
    borderClass: 'border-purple-300/50',
    badgeClass: 'bg-purple-400 text-slate-900',
    glowClass: 'shadow-purple-300/20',
    hex: '#d8b4fe',
  },
  {
    id: 'cyan-light',
    name: 'Cyan Light',
    namePt: 'Ciano Cristalino',
    group: 'light',
    isSubtone: true,
    parentColorId: 'cyan',
    bgClass: 'bg-cyan-300/20',
    textClass: 'text-cyan-700 dark:text-cyan-300',
    borderClass: 'border-cyan-300/50',
    badgeClass: 'bg-cyan-400 text-slate-900',
    glowClass: 'shadow-cyan-300/20',
    hex: '#67e8f9',
  },
  {
    id: 'slate-light',
    name: 'Platinum Light',
    namePt: 'Platina Clara',
    group: 'light',
    isSubtone: true,
    parentColorId: 'slate',
    bgClass: 'bg-slate-300/20',
    textClass: 'text-slate-700 dark:text-slate-300',
    borderClass: 'border-slate-300/50',
    badgeClass: 'bg-slate-400 text-slate-900',
    glowClass: 'shadow-slate-300/20',
    hex: '#cbd5e1',
  },
  {
    id: 'red-light',
    name: 'Coral Light',
    namePt: 'Coral Suave',
    group: 'light',
    isSubtone: true,
    parentColorId: 'red',
    bgClass: 'bg-red-300/20',
    textClass: 'text-red-700 dark:text-red-300',
    borderClass: 'border-red-300/50',
    badgeClass: 'bg-red-400 text-slate-900',
    glowClass: 'shadow-red-300/20',
    hex: '#fca5a5',
  },
  {
    id: 'orange-light',
    name: 'Tangerine Light',
    namePt: 'Tangerina Clara',
    group: 'light',
    isSubtone: true,
    parentColorId: 'orange',
    bgClass: 'bg-orange-300/20',
    textClass: 'text-orange-700 dark:text-orange-300',
    borderClass: 'border-orange-300/50',
    badgeClass: 'bg-orange-400 text-slate-900',
    glowClass: 'shadow-orange-300/20',
    hex: '#fdba74',
  },
  {
    id: 'lime-light',
    name: 'Spring Lime Light',
    namePt: 'Lima Primaveril Claro',
    group: 'light',
    isSubtone: true,
    parentColorId: 'lime',
    bgClass: 'bg-lime-300/20',
    textClass: 'text-lime-800 dark:text-lime-300',
    borderClass: 'border-lime-300/50',
    badgeClass: 'bg-lime-400 text-slate-900',
    glowClass: 'shadow-lime-300/20',
    hex: '#bef264',
  },
  {
    id: 'gold-light',
    name: 'Champagne Gold Light',
    namePt: 'Champanhe Claro',
    group: 'light',
    isSubtone: true,
    parentColorId: 'gold',
    bgClass: 'bg-yellow-200/20',
    textClass: 'text-yellow-800 dark:text-yellow-300',
    borderClass: 'border-yellow-200/50',
    badgeClass: 'bg-yellow-300 text-slate-900',
    glowClass: 'shadow-yellow-200/20',
    hex: '#fef08a',
  },

  // =========================================================================
  // 12 SUBTONS MAIS ESCUROS (DEEP / NOTURNOS)
  // =========================================================================
  {
    id: 'blue-dark',
    name: 'Midnight Blue',
    namePt: 'Azul Meia-Noite',
    group: 'dark',
    isSubtone: true,
    parentColorId: 'blue',
    bgClass: 'bg-blue-900/30',
    textClass: 'text-blue-400 dark:text-blue-300',
    borderClass: 'border-blue-800/60',
    badgeClass: 'bg-blue-900 text-white border border-blue-700',
    glowClass: 'shadow-blue-900/40',
    hex: '#1e3a8a',
  },
  {
    id: 'emerald-dark',
    name: 'Deep Forest',
    namePt: 'Verde Floresta Escuro',
    group: 'dark',
    isSubtone: true,
    parentColorId: 'emerald',
    bgClass: 'bg-emerald-900/30',
    textClass: 'text-emerald-400 dark:text-emerald-300',
    borderClass: 'border-emerald-800/60',
    badgeClass: 'bg-emerald-900 text-white border border-emerald-700',
    glowClass: 'shadow-emerald-900/40',
    hex: '#064e3b',
  },
  {
    id: 'indigo-dark',
    name: 'Midnight Indigo',
    namePt: 'Índigo Noturno',
    group: 'dark',
    isSubtone: true,
    parentColorId: 'indigo',
    bgClass: 'bg-indigo-900/30',
    textClass: 'text-indigo-400 dark:text-indigo-300',
    borderClass: 'border-indigo-800/60',
    badgeClass: 'bg-indigo-900 text-white border border-indigo-700',
    glowClass: 'shadow-indigo-900/40',
    hex: '#312e81',
  },
  {
    id: 'amber-dark',
    name: 'Burnt Amber',
    namePt: 'Âmbar Queimado',
    group: 'dark',
    isSubtone: true,
    parentColorId: 'amber',
    bgClass: 'bg-amber-900/30',
    textClass: 'text-amber-400 dark:text-amber-300',
    borderClass: 'border-amber-800/60',
    badgeClass: 'bg-amber-900 text-white border border-amber-700',
    glowClass: 'shadow-amber-900/40',
    hex: '#78350f',
  },
  {
    id: 'rose-dark',
    name: 'Deep Wine Ruby',
    namePt: 'Vinho Rubi Escuro',
    group: 'dark',
    isSubtone: true,
    parentColorId: 'rose',
    bgClass: 'bg-rose-900/30',
    textClass: 'text-rose-400 dark:text-rose-300',
    borderClass: 'border-rose-800/60',
    badgeClass: 'bg-rose-900 text-white border border-rose-700',
    glowClass: 'shadow-rose-900/40',
    hex: '#881337',
  },
  {
    id: 'purple-dark',
    name: 'Imperial Purple',
    namePt: 'Púrpura Imperial Escura',
    group: 'dark',
    isSubtone: true,
    parentColorId: 'purple',
    bgClass: 'bg-purple-900/30',
    textClass: 'text-purple-400 dark:text-purple-300',
    borderClass: 'border-purple-800/60',
    badgeClass: 'bg-purple-900 text-white border border-purple-700',
    glowClass: 'shadow-purple-900/40',
    hex: '#581c87',
  },
  {
    id: 'cyan-dark',
    name: 'Abyssal Cyan',
    namePt: 'Oceano Abissal Escuro',
    group: 'dark',
    isSubtone: true,
    parentColorId: 'cyan',
    bgClass: 'bg-cyan-900/30',
    textClass: 'text-cyan-400 dark:text-cyan-300',
    borderClass: 'border-cyan-800/60',
    badgeClass: 'bg-cyan-900 text-white border border-cyan-700',
    glowClass: 'shadow-cyan-900/40',
    hex: '#164e63',
  },
  {
    id: 'slate-dark',
    name: 'Mineral Charcoal',
    namePt: 'Carvão Mineral Escuro',
    group: 'dark',
    isSubtone: true,
    parentColorId: 'slate',
    bgClass: 'bg-slate-900/30',
    textClass: 'text-slate-400 dark:text-slate-300',
    borderClass: 'border-slate-800/60',
    badgeClass: 'bg-slate-900 text-white border border-slate-700',
    glowClass: 'shadow-slate-900/40',
    hex: '#1e293b',
  },
  {
    id: 'red-dark',
    name: 'Deep Crimson',
    namePt: 'Carmesim Noturno',
    group: 'dark',
    isSubtone: true,
    parentColorId: 'red',
    bgClass: 'bg-red-900/30',
    textClass: 'text-red-400 dark:text-red-300',
    borderClass: 'border-red-800/60',
    badgeClass: 'bg-red-900 text-white border border-red-700',
    glowClass: 'shadow-red-900/40',
    hex: '#7f1d1d',
  },
  {
    id: 'orange-dark',
    name: 'Deep Terracotta',
    namePt: 'Terracota Escura',
    group: 'dark',
    isSubtone: true,
    parentColorId: 'orange',
    bgClass: 'bg-orange-900/30',
    textClass: 'text-orange-400 dark:text-orange-300',
    borderClass: 'border-orange-800/60',
    badgeClass: 'bg-orange-900 text-white border border-orange-700',
    glowClass: 'shadow-orange-900/40',
    hex: '#7c2d12',
  },
  {
    id: 'lime-dark',
    name: 'Dark Moss',
    namePt: 'Musgo Florestal Escuro',
    group: 'dark',
    isSubtone: true,
    parentColorId: 'lime',
    bgClass: 'bg-lime-900/30',
    textClass: 'text-lime-400 dark:text-lime-300',
    borderClass: 'border-lime-800/60',
    badgeClass: 'bg-lime-900 text-white border border-lime-700',
    glowClass: 'shadow-lime-900/40',
    hex: '#365314',
  },
  {
    id: 'gold-dark',
    name: 'Aged Bronze',
    namePt: 'Bronze Envelhecido',
    group: 'dark',
    isSubtone: true,
    parentColorId: 'gold',
    bgClass: 'bg-yellow-900/30',
    textClass: 'text-yellow-400 dark:text-yellow-300',
    borderClass: 'border-yellow-800/60',
    badgeClass: 'bg-yellow-900 text-white border border-yellow-700',
    glowClass: 'shadow-yellow-900/40',
    hex: '#713f12',
  },
];

export interface CheckpointIconOption {
  id: string;
  name: string;
  namePt: string;
  category: 'emotions' | 'leisure' | 'nature' | 'office' | 'gastronomy';
  icon: LucideIcon;
}

export const CHECKPOINT_ICON_CATEGORIES = [
  { id: 'emotions', namePt: 'Emoções Completas', nameEn: 'Complete Emotions' },
  { id: 'leisure', namePt: 'Lazer, Família & Casa', nameEn: 'Leisure, Family & Home' },
  { id: 'nature', namePt: 'Natureza, Tempo & Estações', nameEn: 'Nature, Weather & Seasons' },
  { id: 'office', namePt: 'Escritório & Foco', nameEn: 'Office & Focus' },
  { id: 'gastronomy', namePt: 'Gastronomia & Nutrição', nameEn: 'Gastronomy & Nutrition' },
] as const;

export const CHECKPOINT_ICONS: CheckpointIconOption[] = [
  // =========================================================================
  // 1. EMOÇÕES COMPLETAS (Gama rica de sentimentos e estados)
  // =========================================================================
  { id: 'smile', name: 'Joy', namePt: 'Alegria / Contentamento', category: 'emotions', icon: Smile },
  { id: 'laugh', name: 'Euphoria', namePt: 'Riso / Euforia / Celebração', category: 'emotions', icon: Laugh },
  { id: 'heart', name: 'Love', namePt: 'Amor / Afeto / Carinho', category: 'emotions', icon: Heart },
  { id: 'hearthandshake', name: 'Trust', namePt: 'Confiança / Parceria / Gratidão', category: 'emotions', icon: HeartHandshake },
  { id: 'smileplus', name: 'Enthusiasm', namePt: 'Entusiasmo / Motivação', category: 'emotions', icon: SmilePlus },
  { id: 'flame', name: 'Passion', namePt: 'Paixão / Vontade Intensa', category: 'emotions', icon: Flame },
  { id: 'zap', name: 'Awakening', namePt: 'Surpresa / Despertar / Energia', category: 'emotions', icon: Zap },
  { id: 'sparkles', name: 'Inspiration', namePt: 'Inspiração / Alinhamento', category: 'emotions', icon: Sparkles },
  { id: 'shield', name: 'Peace', namePt: 'Serenidade / Neutralidade / Calma', category: 'emotions', icon: ShieldCheck },
  { id: 'brain', name: 'Reflection', namePt: 'Reflexão / Pensamento / Insight', category: 'emotions', icon: Brain },
  { id: 'eye', name: 'Presence', namePt: 'Presença Consciente / Atenção', category: 'emotions', icon: Eye },
  { id: 'alertcircle', name: 'Caution', namePt: 'Cautela / Alerta / Prudência', category: 'emotions', icon: AlertCircle },
  { id: 'cloudrain_em', name: 'Empathy', namePt: 'Acolhimento / Vulnerabilidade / Tristeza', category: 'emotions', icon: CloudRain },
  { id: 'partypopper', name: 'Triumph', namePt: 'Orgulho / Triunfo / Vitória', category: 'emotions', icon: PartyPopper },

  // =========================================================================
  // 2. LAZER, FAMÍLIA & CASA (Família, Casa, Criança, Pet, Esportes, Viagem)
  // =========================================================================
  { id: 'home', name: 'Home', namePt: 'Casa / Lar / Conforto', category: 'leisure', icon: Home },
  { id: 'users', name: 'Family', namePt: 'Família / Amigos / Encontro', category: 'leisure', icon: Users },
  { id: 'baby', name: 'Child', namePt: 'Criança / Cuidado / Paternidade', category: 'leisure', icon: Baby },
  { id: 'cat', name: 'Pet Cat', namePt: 'Pet / Gato / Afeto', category: 'leisure', icon: Cat },
  { id: 'dog', name: 'Pet Dog', namePt: 'Pet / Cão / Companheirismo', category: 'leisure', icon: Dog },
  { id: 'gamepad', name: 'Gaming', namePt: 'Jogos / Descontração', category: 'leisure', icon: Gamepad2 },
  { id: 'dumbbell', name: 'Workout', namePt: 'Treino / Musculação / Fitness', category: 'leisure', icon: Dumbbell },
  { id: 'music', name: 'Music', namePt: 'Música / Harmonia / Show', category: 'leisure', icon: Music },
  { id: 'film', name: 'Cinema', namePt: 'Filmes / Séries / Cinema', category: 'leisure', icon: Film },
  { id: 'book', name: 'Reading', namePt: 'Leitura / Estudo Pessoal', category: 'leisure', icon: BookOpen },
  { id: 'plane', name: 'Travel', namePt: 'Viagem / Férias / Roteiro', category: 'leisure', icon: Plane },
  { id: 'bike', name: 'Cycling', namePt: 'Ciclismo / Passeio ao Ar Livre', category: 'leisure', icon: Bike },
  { id: 'camera', name: 'Photography', namePt: 'Fotografia / Memórias', category: 'leisure', icon: Camera },
  { id: 'tv', name: 'Entertainment', namePt: 'Descanso / Entretenimento', category: 'leisure', icon: Tv },
  { id: 'palmtree', name: 'Beach', namePt: 'Praia / Descanso Tropical', category: 'leisure', icon: Palmtree },
  { id: 'trophy', name: 'Trophy', namePt: 'Conquista / Troféu Pessoal', category: 'leisure', icon: Trophy },

  // =========================================================================
  // 3. NATUREZA, TEMPO & ESTAÇÕES (Sol, Chuva, Neve, Vento, Estações, Elementos)
  // =========================================================================
  { id: 'sun', name: 'Summer Sun', namePt: 'Sol / Verão / Dia Ensolarado', category: 'nature', icon: Sun },
  { id: 'sunrise', name: 'Dawn', namePt: 'Amanhecer / Alvorada', category: 'nature', icon: Sunrise },
  { id: 'sunset', name: 'Sunset', namePt: 'Pôr do Sol / Entardecer', category: 'nature', icon: Sunset },
  { id: 'moon', name: 'Night Moon', namePt: 'Lua / Noite / Céu Noturno', category: 'nature', icon: Moon },
  { id: 'cloudsun', name: 'Mild Weather', namePt: 'Tempo Parcialmente Nublado', category: 'nature', icon: CloudSun },
  { id: 'cloudrain', name: 'Rain', namePt: 'Chuva / Dia Chuvoso', category: 'nature', icon: CloudRain },
  { id: 'cloudlightning', name: 'Storm', namePt: 'Tempestade / Trovoadas', category: 'nature', icon: CloudLightning },
  { id: 'snowflake', name: 'Winter Snow', namePt: 'Neve / Inverno / Frio', category: 'nature', icon: Snowflake },
  { id: 'wind', name: 'Autumn Wind', namePt: 'Vento / Outono / Mente Fluida', category: 'nature', icon: Wind },
  { id: 'flower', name: 'Spring Flower', namePt: 'Flor / Primavera / Desabrochar', category: 'nature', icon: Flower2 },
  { id: 'leaf', name: 'Leaf', namePt: 'Folhagem / Outono / Renovação', category: 'nature', icon: Leaf },
  { id: 'trees', name: 'Forest', namePt: 'Floresta / Bosque / Conexão Natural', category: 'nature', icon: Trees },
  { id: 'mountain', name: 'Mountain', namePt: 'Montanha / Firmeza / Altitude', category: 'nature', icon: Mountain },
  { id: 'waves', name: 'Ocean Waves', namePt: 'Ondas / Mar / Maré', category: 'nature', icon: Waves },
  { id: 'droplets', name: 'Water Flow', namePt: 'Gotas de Água / Fluidez', category: 'nature', icon: Droplets },
  { id: 'sprout', name: 'Sprout', namePt: 'Broto / Novo Ciclo / Semeadura', category: 'nature', icon: Sprout },
  { id: 'bird', name: 'Bird', namePt: 'Pássaro / Liberdade / Voo', category: 'nature', icon: Bird },
  { id: 'feather', name: 'Feather', namePt: 'Pena / Leveza / Ar', category: 'nature', icon: Feather },

  // =========================================================================
  // 4. ESCRITÓRIO & FOCO
  // =========================================================================
  { id: 'target', name: 'Target', namePt: 'Meta / Foco Nobre', category: 'office', icon: Target },
  { id: 'briefcase', name: 'Briefcase', namePt: 'Trabalho / Execução / Projetos', category: 'office', icon: Briefcase },
  { id: 'laptop', name: 'Laptop', namePt: 'Computador / Digital / Tech', category: 'office', icon: Laptop },
  { id: 'listtodo', name: 'Task List', namePt: 'Lista de Tarefas / Checklist', category: 'office', icon: ListTodo },
  { id: 'filetext', name: 'Document', namePt: 'Relatório / Síntese / Documento', category: 'office', icon: FileText },
  { id: 'presentation', name: 'Meeting', namePt: 'Apresentação / Reunião Estratégica', category: 'office', icon: Presentation },
  { id: 'calendar', name: 'Calendar', namePt: 'Agenda / Cronograma / Prazos', category: 'office', icon: Calendar },
  { id: 'rocket', name: 'Launch', namePt: 'Lançamento / Entrega de Alto Impacto', category: 'office', icon: Rocket },
  { id: 'trendingup', name: 'Growth', namePt: 'Métricas / Crescimento / Resultados', category: 'office', icon: TrendingUp },
  { id: 'barchart', name: 'Analytics', namePt: 'Análise de Desempenho', category: 'office', icon: BarChart2 },
  { id: 'clock', name: 'Time Tracking', namePt: 'Gestão do Tempo / Pontualidade', category: 'office', icon: Clock },
  { id: 'compass', name: 'Strategy', namePt: 'Bússola / Direcionamento Estratégico', category: 'office', icon: Compass },
  { id: 'folder', name: 'Folder', namePt: 'Arquivo / Organização de Dados', category: 'office', icon: Folder },
  { id: 'flag', name: 'Milestone', namePt: 'Marco Concluído / Bandeira', category: 'office', icon: Flag },
  { id: 'check', name: 'Checkmark', namePt: 'Vitória / Concluído', category: 'office', icon: CheckCircle2 },

  // =========================================================================
  // 5. GASTRONOMIA & NUTRIÇÃO
  // =========================================================================
  { id: 'utensils', name: 'Dining', namePt: 'Refeição / Gastronomia', category: 'gastronomy', icon: Utensils },
  { id: 'coffee', name: 'Coffee', namePt: 'Café / Ritual Matinal', category: 'gastronomy', icon: Coffee },
  { id: 'salad', name: 'Healthy Salad', namePt: 'Salada / Vitalidade Nutricional', category: 'gastronomy', icon: Salad },
  { id: 'apple', name: 'Fruit', namePt: 'Fruta / Nutrição Limpa', category: 'gastronomy', icon: Apple },
  { id: 'wine', name: 'Wine', namePt: 'Vinho / Degustação / Brinde', category: 'gastronomy', icon: Wine },
  { id: 'beer', name: 'Beer', namePt: 'Cerveja / Happy Hour', category: 'gastronomy', icon: Beer },
  { id: 'pizza', name: 'Pizza', namePt: 'Pizza / Jantar Descontraído', category: 'gastronomy', icon: Pizza },
  { id: 'sandwich', name: 'Sandwich', namePt: 'Lanche Saudável', category: 'gastronomy', icon: Sandwich },
  { id: 'soup', name: 'Soup', namePt: 'Sopa / Caldo / Conforto', category: 'gastronomy', icon: Soup },
  { id: 'cake', name: 'Cake', namePt: 'Bolo / Comemoração', category: 'gastronomy', icon: Cake },
  { id: 'cookie', name: 'Cookie', namePt: 'Doce / Pequeno Prazer', category: 'gastronomy', icon: Cookie },
  { id: 'cupsoda', name: 'Hydration', namePt: 'Bebida / Hidratação', category: 'gastronomy', icon: CupSoda },
];

export interface SelectableJournalComponent {
  key: string;
  title: string;
  titleEn: string;
  summary: string;
  summaryEn: string;
  category: 'consciousness' | 'synthesis' | 'alchemy' | 'windows' | 'frequency' | 'spheres';
  tag: string;
  icon: LucideIcon;
}

export const DAILY_JOURNAL_AVAILABLE_COMPONENTS: SelectableJournalComponent[] = [
  {
    key: 'consciousness_level',
    title: 'Estado de Consciência (Nível 350 — Aceitação)',
    titleEn: 'Consciousness State (Level 350 — Acceptance)',
    summary: 'Perdão, harmonia, transcendência. Segundo limiar de despertar e ausência de conflito interno.',
    summaryEn: 'Forgiveness, harmony, transcendence. Second awakening threshold and inner alignment.',
    category: 'consciousness',
    tag: 'CALIBRAÇÃO',
    icon: Activity,
  },
  {
    key: 'daily_synthesis',
    title: 'Síntese Soberana do Dia',
    titleEn: 'Sovereign Daily Synthesis',
    summary: 'Janela matinal favorável para trabalho analítico profundo, decisões estruturantes e preservação de vigor.',
    summaryEn: 'Morning prime window for deep analytical focus, structural decisions and somatic vigor.',
    category: 'synthesis',
    tag: 'SÍNTESE',
    icon: FileText,
  },
  {
    key: 'alchemy_metrics',
    title: 'Alquimia dos 4 Elementos (Terra 71%, Fogo 56%)',
    titleEn: '4 Elements Alchemy (Earth 71%, Fire 56%)',
    summary: 'Predomínio de ancoragem prática, disciplina material e clareza de execução.',
    summaryEn: 'Predominance of practical grounding, material discipline and execution clarity.',
    category: 'alchemy',
    tag: 'ALQUIMIA',
    icon: Layers,
  },
  {
    key: 'day_windows',
    title: 'Janelas do Ritmo Solar (Manhã 08-12h Produtiva)',
    titleEn: 'Solar Rhythm Windows (Morning 08-12h Peak)',
    summary: 'Curva circadiana com pico de entrega matinal e janela de descompressão vespertina.',
    summaryEn: 'Circadian curve with morning delivery peak and afternoon somatic decompression.',
    category: 'windows',
    tag: 'RITMO',
    icon: Calendar,
  },
  {
    key: 'sound_frequency',
    title: 'Frequência Sonora Neuroacústica (528 Hz)',
    titleEn: 'Neuroacoustic Sound Frequency (528 Hz)',
    summary: 'Ressonância binaural para reparação, clareza intuitiva e foco sem ansiedade.',
    summaryEn: 'Binaural resonance for restoration, intuitive clarity and calm focus.',
    category: 'frequency',
    tag: 'FREQUÊNCIA',
    icon: Volume2,
  },
  {
    key: 'spheres',
    title: 'Esferas do Dia (Carreira, Social, Saúde)',
    titleEn: 'Daily Spheres (Career, Social, Somatic)',
    summary: 'Proteção do bloco 08:00-10:00 para tarefa única e alinhamentos estratégicos bilaterais.',
    summaryEn: 'Single-task protection for 08:00-10:00 block and strategic bilateral syncs.',
    category: 'spheres',
    tag: 'ESFERAS',
    icon: Target,
  },
];

export interface HabitOption {
  id: string;
  labelPt: string;
  labelEn: string;
  icon: LucideIcon;
}

export const DAILY_HABITS_LIST: HabitOption[] = [
  { id: 'deep_work', labelPt: 'Bloco de Foco Profundo (25m)', labelEn: 'Deep Work Block (25m)', icon: Target },
  { id: 'hydration', labelPt: 'Hidratação & Vigor Somático', labelEn: 'Hydration & Somatic Vigor', icon: HeartPulse },
  { id: 'active_listening', labelPt: 'Escuta Ativa & Alinhamento', labelEn: 'Active Listening & Sync', icon: ShieldCheck },
  { id: 'meditation', labelPt: 'Pausa de Presença / Respiração', labelEn: 'Presence / Breathing Pause', icon: Moon },
  { id: 'neuroacustica', labelPt: 'Sessão Neuroacústica (528 Hz)', labelEn: 'Neuroacoustic Session', icon: Volume2 },
];
